# https://docs.gitlab.com/ee/ci/git_submodules.html
variables:
  GIT_DEPTH: 100
  GIT_SUBMODULE_STRATEGY: normal

.test:
  artifacts:
    expire_in: 2 weeks
    when: always
    paths:
    - "*.tar.gz"
    - ./*.log
    - ./config.h
    - ./**/*.log

Debian:
  extends: .test
  image: debian:latest
  stage: build
  before_script:
  - apt-get update -qq
  - env DEBIAN_FRONTEND=noninteractive apt-get install -y -qq git autoconf automake libtool make valgrind
  script:
  - ./bootstrap
  - ./configure WARN_CFLAGS=-Werror
  - make syntax-check
  - make
  - make check || (find . -name test-suite.log -exec cat {} +; exit 1)
  - make dist
  - sha224sum libntlm-*.tar.gz

# https://docs.gitlab.com/ee/ci/runners/saas/macos/environment.html
Macos11xcode12:
  extends: .test
  stage: build
  tags: [ shared-macos-amd64 ]
  image: macos-11-xcode-12
  script:
  - ./bootstrap
  - ./configure WARN_CFLAGS=-Werror
  - make syntax-check
  - make
  - make check || (find . -name test-suite.log -exec cat {} +; exit 1)
  - make dist
  - sha224sum libntlm-*.tar.gz
