# Copyright (C) 2018-2024 Simon Josefsson.
#
# This file is part of Libntlm.
#
# Libntlm is free software; you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as
# published by the Free Software Foundation; either version 2.1 of
# the License, or (at your option) any later version.
#
# Libntlm is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with Libntlm; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301,
# USA

variables:
  GNULIB_URL: https://gitlab.com/libidn/gnulib-mirror.git

default:
  interruptible: true
  artifacts:
    expire_in: 2 weeks
    when: always
    paths:
    - "*.tar.gz"
    - ./*.log
    - ./config.h
    - ./**/*.log

B-gcc:
  image: gcc:latest
  stage: build
  before_script:
  - apt-get update -qq
  - apt-get install -qqy --no-install-recommends git autoconf automake libtool make valgrind
  script:
  - gcc --version
  - ./bootstrap
  - ./configure CC="gcc -std=gnu2x" --enable-gcc-warnings WARN_CFLAGS=-Werror
  - make -j$(nproc) V=1
  - make -j$(nproc) V=1 distcheck VERBOSE=t
  - make -f cfg.mk srcdist
  - sha256sum libntlm-*.tar.gz
  - git status
  - git diff --exit-code

B-clang:
  image: silkeh/clang:latest
  stage: build
  before_script:
  - apt-get update -qq
  - apt-get install -qqy --no-install-recommends git autoconf automake libtool make
  script:
  - clang --version
  - ./bootstrap
  - ./configure CC="clang -std=gnu2x" --enable-gcc-warnings WARN_CFLAGS=-Werror
  - make -j$(nproc) V=1
  - make -j$(nproc) V=1 distcheck VERBOSE=t
  - make -f cfg.mk srcdist
  - sha256sum libntlm-*.tar.gz
  - git status
  - git diff --exit-code

B-Alpine:
  image: alpine:latest
  stage: build
  needs: [B-Trisquel11]
  before_script:
  - apk update
  - apk add build-base git autoconf automake libtool make coreutils valgrind
  script:
  - ./bootstrap
  - ./configure --enable-gcc-warnings WARN_CFLAGS=-Werror
  - make -j$(nproc) V=1
  - make syntax-check
  - make -j$(nproc) V=1 check VERBOSE=t
  - make -f cfg.mk srcdist
  - sha256sum libntlm-*.tar.gz
  - git status
  - git diff --exit-code

B-Debian-latest:
  image: debian:latest
  stage: build
  before_script:
  - apt-get update -qq
  - apt-get install -qqy --no-install-recommends git autoconf automake libtool make valgrind ca-certificates
  script:
  - ./bootstrap
  - ./configure --enable-gcc-warnings WARN_CFLAGS=-Werror
  - make syntax-check
  - make -j$(nproc) V=1
  - make -j$(nproc) V=1 check VERBOSE=t
  - make -j$(nproc) V=1 distcheck
  - make -f cfg.mk srcdist
  - sha256sum libntlm-*.tar.gz
  - git status
  - git diff --exit-code

B-Debian-testing:
  image: debian:testing-slim
  stage: build
  before_script:
  - apt-get update -qq
  - apt-get install -qqy --no-install-recommends git autoconf automake libtool make valgrind indent ca-certificates
  script:
  - ./bootstrap
  - ./configure --enable-gcc-warnings WARN_CFLAGS=-Werror
  - make -j$(nproc) V=1
  - make syntax-check
  - make -j$(nproc) V=1 check VERBOSE=t
  - make -j$(nproc) V=1 distcheck
  - make -f cfg.mk srcdist
  - sha256sum libntlm-*.tar.gz
  - git status
  - git diff --exit-code

B-Trisquel11:
  image: kpengboy/trisquel:11.0
  tags: [ saas-linux-medium-amd64 ]
  stage: build
  before_script:
  - apt-get update -qq
  - apt-get install -qqy --no-install-recommends git autoconf automake libtool make valgrind ca-certificates
  script:
  - ./bootstrap
  - ./configure --enable-gcc-warnings WARN_CFLAGS=-Werror
  - make -j$(nproc) V=1
  - make -j$(nproc) V=1 check VERBOSE=t
  - make syntax-check
  - make -j$(nproc) V=1 distcheck
  - make -f cfg.mk srcdist
  - sha256sum libntlm-*.tar.gz
  - git status
  - git diff --exit-code

# https://docs.gitlab.com/ee/ci/runners/saas/macos/environment.html
B-macOS14Xcode15:
  stage: build
  image: macos-14-xcode-15
  tags: [ saas-macos-medium-m1 ]
  variables:
    HOMEBREW_NO_AUTO_UPDATE: 1
    HOMEBREW_NO_INSTALL_UPGRADE: 1
    HOMEBREW_NO_INSTALL_CLEANUP: 1
    HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 1
  before_script:
  - brew install autoconf automake libtool
  script:
  - ./bootstrap
  - ./configure --enable-gcc-warnings WARN_CFLAGS=-Werror
  - make -j$(nproc) V=1
  - make -j$(nproc) V=1 distcheck VERBOSE=t
  - make syntax-check
  - make dist
  - make -f cfg.mk srcdist
  - sha256sum libntlm-*.tar.gz
  - git status
  - git diff --exit-code

# https://docs.gitlab.com/ee/ci/runners/saas/windows_saas_runner.html
B-Windows-UCRT64:
  tags: [ shared-windows, windows-1809 ]
  stage: build
  script: # https://www.msys2.org/docs/ci/#other-systems
  - wget.exe --no-check-certificate -nv -O msys2.exe https://github.com/msys2/msys2-installer/releases/download/nightly-x86_64/msys2-base-x86_64-latest.sfx.exe
  - ./msys2.exe -y -oC:\
  - Remove-Item msys2.exe
  - $env:CHERE_INVOKING = 'yes'
  - $env:MSYSTEM = 'UCRT64' # https://www.msys2.org/docs/environments/
  - C:\msys64\usr\bin\bash -lc ' '
  - C:\msys64\usr\bin\bash -lc 'pacman --noconfirm -Syuu'
  - C:\msys64\usr\bin\bash -lc 'pacman --noconfirm -Syuu'
  - |
    C:\msys64\usr\bin\bash -lcx '
    pacman --noconfirm -Syu git autoconf automake libtool make mingw-w64-ucrt-x86_64-gcc
    ./bootstrap
    ./configure
    make V=1 check VERBOSE=t'

AlmaLinux8:
  image: almalinux:8
  stage: test
  needs: [B-Trisquel11]
  before_script:
  - yum -y install make gcc
  script:
  - tar xfa libntlm-*.tar.gz
  - cd `ls -d libntlm-* | grep -v tar.gz`
  - ./configure --enable-gcc-warnings
  - make syntax-check
  - make -j$(nproc) V=1 distcheck VERBOSE=t
  - sha256sum libntlm-*.tar.gz

Alpine:
  image: alpine:latest
  stage: test
  needs: [B-Trisquel11]
  before_script:
  - apk update
  - apk add build-base valgrind
  script:
  - tar xfa libntlm-*.tar.gz
  - cd `ls -d libntlm-* | grep -v tar.gz`
  - ./configure --enable-gcc-warnings
  - make syntax-check
  - make -j$(nproc) V=1 check VERBOSE=t

ArchLinux:
  image: archlinux:latest
  stage: test
  needs: [B-Trisquel11]
  before_script:
  - pacman -Syu --noconfirm make gcc
  script:
  - tar xfa libntlm-*.tar.gz
  - cd `ls -d libntlm-* | grep -v tar.gz`
  - mkdir b
  - cd b
  - ../configure --enable-gcc-warnings
  - make syntax-check
  - make -j$(nproc) V=1 distcheck VERBOSE=t
  - sha256sum libntlm-*.tar.gz

macOS13Xcode14:
  image: macos-13-xcode-14
  tags: [ saas-macos-medium-m1 ]
  stage: test
  needs: [B-Trisquel11]
  script:
  - gzip -cd libntlm-*.tar.gz | tar xf -
  - cd `ls -d libntlm-* | grep -v tar.gz`
  - mkdir b
  - cd b
  - ../configure --enable-gcc-warnings
  - make syntax-check
  - make -j$(nproc) V=1 distcheck VERBOSE=t
  - sha256sum libntlm-*.tar.gz

CentOS7:
  image: centos:7
  stage: test
  needs: [B-Trisquel11]
  before_script:
  - yum -y install make gcc
  script:
  - tar xfa libntlm-*.tar.gz
  - cd `ls -d libntlm-* | grep -v tar.gz`
  - mkdir b
  - cd b
  - ../configure --enable-gcc-warnings
  - make syntax-check
  - make -j$(nproc) V=1 check VERBOSE=t

Fedora39:
  image: fedora:39
  stage: test
  needs: [B-Trisquel11]
  before_script:
  - dnf update -y
  - dnf install -y gcc make
  script:
  - tar xfa libntlm-*.tar.gz
  - cd `ls -d libntlm-* | grep -v tar.gz`
  - ./configure --enable-gcc-warnings
  - make syntax-check
  - make -j$(nproc) V=1 distcheck VERBOSE=t
  - sha256sum libntlm-*.tar.gz

Windows-MINGW64:
  tags: [ shared-windows, windows-1809 ]
  stage: test
  needs: [B-Trisquel11]
  script: # https://www.msys2.org/docs/ci/#other-systems
  - wget.exe --no-check-certificate -nv -O msys2.exe https://github.com/msys2/msys2-installer/releases/download/nightly-x86_64/msys2-base-x86_64-latest.sfx.exe
  - ./msys2.exe -y -oC:\
  - Remove-Item msys2.exe
  - $env:CHERE_INVOKING = 'yes'
  - $env:MSYSTEM = 'MINGW64' # https://www.msys2.org/docs/environments/
  - C:\msys64\usr\bin\bash -lc ' '
  - C:\msys64\usr\bin\bash -lc 'pacman --noconfirm -Syuu'
  - C:\msys64\usr\bin\bash -lc 'pacman --noconfirm -Syuu'
  - |
    C:\msys64\usr\bin\bash -lcx '
    pacman --noconfirm -Syu  make mingw-w64-x86_64-gcc
    tar xfa libntlm-*.tar.gz
    cd `ls -d libntlm-* | grep -v tar.gz`
    ./configure --enable-gcc-warnings
    make V=1 check VERBOSE=t'

Ubuntu-rolling:
  image: ubuntu:rolling
  stage: test
  needs: [B-Trisquel11]
  before_script:
  - apt-get update -qq
  - apt-get install -qqy make gcc
  script:
  - tar xfa libntlm-*.tar.gz
  - cd `ls -d libntlm-* | grep -v tar.gz`
  - ./configure
  - make syntax-check
  - make -j$(nproc) V=1 distcheck VERBOSE=t
  - sha256sum libntlm-*.tar.gz
